name: Build Dayton RSS

on:
  schedule:
    # ~06:05 ET in DST ≈ 10:05 UTC; in Standard Time ≈ 11:05 UTC
    - cron: "5 10 * * *"
    - cron: "5 11 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Build feed
        run: python scripts/build_feed.py

      - name: Commit and push if changed
        run: |
          if [[ -n "$(git status --porcelain feed.xml)" ]]; then
            git config user.name "github-actions[bot]"
            git config user.email "github-actions[bot]@users.noreply.github.com"
            git add feed.xml
            git commit -m "Auto-update feed.xml"
            git push
          fi
