name: Build Dayton RSS

on:
  schedule:
    - cron: "5 10 * * *"
    - cron: "5 11 * * *"
  workflow_dispatch:

permissions:
  contents: write

steps:
  - uses: actions/checkout@v4
    with:
      fetch-depth: 0
      clean: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: true
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Build feed
        run: python scripts/build_feed.py

- name: Commit and push if changed
  shell: bash
  run: |
    git config user.name "github-actions[bot]"
    git config user.email "github-actions[bot]@users.noreply.github.com"
    git fetch origin main
    git pull --rebase --autostash origin main
    if ! git diff --quiet -- feed.xml; then
      git add feed.xml
      git commit -m "Auto-update feed.xml"
      git push origin HEAD:main
    else
      echo "No changes to commit."
    fi

